// <autogenerated />
namespace File_32_Input_32__40_in_45_memory_41_
{
	partial class SetRunDelayForm
	{
		/// <summary>
		/// Designer variable used to keep track of non-visual components.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Disposes resources used by the form.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing) {
				if (components != null) {
					components.Dispose();
				}
			}
			base.Dispose(disposing);
		}
		
		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent()
		{
			this.editDelayLabel = new System.Windows.Forms.Label();
			this.setValueButton = new System.Windows.Forms.Button();
			this.editDelayComboBox = new System.Windows.Forms.ComboBox();
			this.SuspendLayout();
			// 
			// editDelayLabel
			// 
			this.editDelayLabel.Location = new System.Drawing.Point(7, 6);
			this.editDelayLabel.Name = "editDelayLabel";
			this.editDelayLabel.Size = new System.Drawing.Size(98, 23);
			this.editDelayLabel.TabIndex = 0;
			this.editDelayLabel.Text = "Edit delay:";
			// 
			// setValueButton
			// 
			this.setValueButton.Location = new System.Drawing.Point(7, 36);
			this.setValueButton.Name = "setValueButton";
			this.setValueButton.Size = new System.Drawing.Size(214, 38);
			this.setValueButton.TabIndex = 1;
			this.setValueButton.Text = "Set value";
			this.setValueButton.UseVisualStyleBackColor = true;
			this.setValueButton.Click += new System.EventHandler(this.OnSetValueButtonClick);
			// 
			// editDelayComboBox
			// 
			this.editDelayComboBox.FormattingEnabled = true;
			this.editDelayComboBox.Items.AddRange(new object[] {
									"50",
									"100",
									"150",
									"200",
									"250",
									"300",
									"350",
									"400",
									"450",
									"500",
									"600",
									"700",
									"800",
									"900",
									"1000",
									"1500",
									"2000",
									"3000",
									"4000",
									"5000"});
			this.editDelayComboBox.Location = new System.Drawing.Point(99, 4);
			this.editDelayComboBox.Name = "editDelayComboBox";
			this.editDelayComboBox.Size = new System.Drawing.Size(121, 28);
			this.editDelayComboBox.TabIndex = 2;
			// 
			// SetRunDelayForm
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 20F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(229, 79);
			this.Controls.Add(this.editDelayComboBox);
			this.Controls.Add(this.setValueButton);
			this.Controls.Add(this.editDelayLabel);
			this.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.Margin = new System.Windows.Forms.Padding(5, 5, 5, 5);
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "SetRunDelayForm";
			this.Text = "Set run delay";
			this.ResumeLayout(false);
		}
		private System.Windows.Forms.ComboBox editDelayComboBox;
		private System.Windows.Forms.Button setValueButton;
		private System.Windows.Forms.Label editDelayLabel;
	}
}
